'''
Dated: Nov05-2018
Auhor: Mahesh Babu Mariappan (https://www.linkedin.com/in/mahesh-babu-mariappan)
Source code for AI Chatbot

References:
https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DatetimeIndex.html#pandas.DatetimeIndex
http://pandas.pydata.org/pandas-docs/stable/timeseries.html#offset-aliases

Attributes of DatetimeIndex

year	The year of the datetime
month	The month as January=1, December=12
day	The days of the datetime
hour	The hours of the datetime
minute	The minutes of the datetime
second	The seconds of the datetime
microsecond	The microseconds of the datetime
nanosecond	The nanoseconds of the datetime
date	Returns numpy array of python datetime.date objects (namely, the date part of Timestamps without timezone information).
time	Returns numpy array of datetime.time.
dayofyear	The ordinal day of the year
weekofyear	The week ordinal of the year
week	The week ordinal of the year
dayofweek	The day of the week with Monday=0, Sunday=6
weekday	The day of the week with Monday=0, Sunday=6
quarter	The quarter of the date
freq	Return the frequency object if it is set, otherwise None
freqstr	Return the frequency object as a string if it is set, otherwise None
is_month_start	Logical indicating if first day of month (defined by frequency)
is_month_end	Indicator for whether the date is the last day of the month.
is_quarter_start	Indicator for whether the date is the first day of a quarter.
is_quarter_end	Indicator for whether the date is the last day of a quarter.
is_year_start	Indicate whether the date is the first day of a year.
is_year_end	Indicate whether the date is the last day of the year.
is_leap_year	Boolean indicator if the date belongs to a leap year.
inferred_freq	Tries to return a string representing a frequency guess, generated by infer_freq.

Test results:
average balance 2 days --> What was my balance at the start of the month ? (WITHOUT scorer=fuzz.token_sort_ratio)
average balance 2 days --> What is my average account balance over the past 2 days ? (WITH scorer=fuzz.token_sort_ratio)

average last month
[('What was my balance last Monday ?', 53), ('Which category has the highest spend last month ?', 52), ('What is my average account balance over the last month ?', 50)]	### FIXED WITH scorer=fuzz.token_set_ratio

balance end of month
[('What is my average account balance at the end of the month ?', 100), ('What was my balance at the end of last month ?', 100), ('What was my balance at the beginning of the month ?', 89)]



'''

#import matplotlib
#from matplotlib import pyplot as plt
import numpy as np # linear algebra
from fuzzywuzzy import fuzz, process
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import os

def receive_user_questions(df): #returns question
	'''retrieve user entered questions through interactive console '''
	question_dict = {		 "What is my current account balance ?":1,  
					 "What was my balance at the ( start / beginning ) of this month ?":2, 
					 "What was my balance five ( 5 ) days back ( ago ) ?":3, 
					 "What was my balance at the ( start / beginning ) of this week ?":4, 
					 "What was my balance at the end of ( past / last ) week ?":401, 
					 "What was my balance ( past / last ) wednesday ?":5, 
					 "What is my average account balance over the ( last / past ) one ( 1 ) week ?":6, 
					 "What is my average account balance over the ( last / past ) two ( 2 ) days ?":7, 
					 "What is my average account balance over the ( last / past ) month ?":8, 
					 "What is my average account balance at the end of the month ?":801, 
					 "What was my balance at the ( start / beginning ) of ( last / past ) month ?":9,
					 "Which category has the highest spend this month ?":10, 
					 "Which category has the lowest spend this month ?":36, 
					 "Which category has the lowest spend last month ?":37, 
					 "Which category has the highest spend last month ?":38, 
					 "What was my balance at the end of ( last / past ) month ?":12, 
					 "What was my balance yesterday ?":14, 
					 "What was my balance two ( 2 ) days back ( ago ) ?":15, 
					 "What was my balance three ( 3 ) days back ( ago ) ?":16, 
					 "What was my balance four ( 4 ) days back ( ago ) ?":17, 
					 "What was my balance six ( 6 ) days back ( ago ) ?":19, 
					 "What was my balance ( last / past ) Monday ?":21, 
					 "What was my balance ( last / past ) Tuesday ?":22, 
					 "What was my balance ( last / past ) Thursday ?":23, 
					 "What was my balance ( last / past ) Friday ?":24, 
					 "What was my balance ( last / past ) Saturday ?":25, 
					 "What was my balance ( last / past ) Sunday ?":26, 
					 "What is my average account balance over the ( last / past ) two ( 2 ) weeks ?":27, 
					 "What is my average account balance over the ( last / past ) three ( 3 ) weeks ?":28, 
					 "What is my average account balance over the ( last / past ) four ( 4 ) weeks ?":29, 
					 "What is my average account balance over the ( last / past ) three ( 3 ) days ?":30, 
					 "What is my average account balance over the ( last / past ) four ( 4 ) days ?":31, 
					 "What is my average account balance over the ( last / past ) five ( 5 ) days ?":32, 
					 "What is my average account balance over the ( last / past ) six ( 6 ) days ?":33, 
					 "What is my average account balance over the ( last / past ) seven ( 7 ) days ?":34, 
					 "What was my total ( expense / expenses / debit / debits / spend / expenditure / outflow / outflows / outgoing ) this week ?":46, 
					 "What was my total ( expense / expenses / debit / debits / spend / expenditure / outflow / outflows / outgoing ) this month ?":47, 
					 "What was my total ( expense / expenses / debit / debits / spend / expenditure / outflow / outflows / outgoing ) last week ?":48, 
					 "What was my total ( expense / expenses / debit / debits / spend / expenditure / outflow / outflows / outgoing ) last month ?":49, 
					 "how much ( expense / did I spend ) this week ?":46, 
					 "how much ( expense / did I spend ) this month ?":47, 
					 "how much ( expense / did I spend ) last week ?":48, 
					 "how much ( expense / did I spend ) last month ?":49, 
					 "What was my total ( earning / earnings / credit / credits / inbound / inbounds / inflow / inflows ) this week ?":50, 
					 "What was my total ( earning / earnings / credit / credits / inbound / inbounds / inflow / inflows ) this month ?":51, 
					 "What was my total ( earning / earnings / credit / credits / inbound / inbounds / inflow / inflows ) last week ?":52, 
					 "What was my total ( earning / earnings / credit / credits / inbound / inbounds / inflow / inflows ) last month ?":53, 
					 "how much did I ( earn / earning / earnings / credit / credits / inbound / inbounds / inflow / inflows ) this week ?":50, 
					 "how much did I ( earn / earnings / credit / credits / inbound / inbounds / inflow / inflows ) this month ?":51, 
					 "how much did I ( earn / earnings / credit / credits / inbound / inbounds / inflow / inflows ) last week ?":52, 
					 "how much did I ( earn / earnings / credit / credits / inbound / inbounds / inflow / inflows ) last month ?":53, 
					 "Which category has the highest spend this week ?":58, 
					 "Which category has the highest spend last week ?":59, 
					 "Show me all expense categories":60, 
					 "how much did I spend on shopping this week ?":61, 
					 "how much did I spend on shopping this month ?":62, 
					 "how much did I spend on shopping last week ?":63, 
					 "how much did I spend on shopping last month ?":64, 
					 "how much did I spend on restaurant this week ?":65, 
					 "how much did I spend on restaurant this month ?":66, 
					 "how much did I spend on restaurant last week ?":67, 
					 "how much did I spend on restaurant last month ?":68, 
					 "how much did I spend on fuel this week ?":69, 
					 "how much did I spend on fuel this month ?":70, 
					 "how much did I spend on fuel last week ?":71, 
					 "how much did I spend on fuel last month ?":72, 
					 "how much did I spend on entertainment this week ?":73, 
					 "how much did I spend on entertainment this month ?":74, 
					 "how much did I spend on entertainment last week ?":75, 
					 "how much did I spend on entertainment last month ?":76, 
					 "how much did I spend on medical this week ?":77, 
					 "how much did I spend on medical this month ?":78, 
					 "how much did I spend on medical last week ?":79, 
					 "how much did I spend on medical last month ?":80, 
					 "how much did I withdraw from ATM this week ?":81, 
					 "how much did I withdraw from ATM this month ?":82, 
					 "how much did I withdraw from ATM last week ?":83, 
					 "how much did I withdraw from ATM last month ?":84, 
					 "how much did I spend on travel this week ?":85, 
					 "how much did I spend on travel this month ?":86, 
					 "how much did I spend on travel last week ?":87, 
					 "how much did I spend on travel last month ?":88, 
					 "shopping expenses this week ?":61, 
					 "shopping expenses this month ?":62, 
					 "shopping expenses last week ?":63, 
					 "shopping expenses last month ?":64, 
					 "restaurant expenses this week ?":65, 
					 "restaurant expenses this month ?":66, 
					 "restaurant expenses last week ?":67, 
					 "restaurant expenses last month ?":68, 
					 "fuel expenses this week ?":69, 
					 "fuel expenses this month ?":70, 
					 "fuel expenses last week ?":71, 
					 "fuel expenses last month ?":72, 
					 "entertainment expenses this week ?":73, 
					 "entertainment expenses this month ?":74, 
					 "entertainment expenses last week ?":75, 
					 "entertainment expenses last month ?":76, 
					 "medical expenses this week ?":77, 
					 "medical expenses this month ?":78, 
					 "medical expenses last week ?":79, 
					 "medical expenses last month ?":80, 
					 "Withdrawals from ATM this week ?":81, 
					 "Withdrawals from ATM this month ?":82, 
					 "Withdrawals from ATM last week ?":83, 
					 "Withdrawals from ATM last month ?":84, 
					 "travel expenses this week ?":85, 
					 "travel expenses this month ?":86, 
					 "travel expenses last week ?":87, 
					 "travel expenses last month ?":88

			}

	print("Hi, I am your banking chatbot. You can ask me questions about your account statement.\n\n")
	while True:	# infinite loop
		user_question = input("Please enter your question. (Enter q to quit)\nQuestion: ")
		if user_question == "q":
			print("\n\nResponse: \n\nGood Bye\n\n")
			break  # stops the loop
		else:
			'''fuzz_result_3tuple_list -- format --> [('What is my current account balance ?', 100), ('What is my average account balance over the ( last / past ) two ( 2 ) weeks ?', 64), ('What was my balance five ( 5 ) days back ( ago ) ?', 64)]'''

			fuzz_result_3tuple_list = process.extract(user_question, list(question_dict.keys()), scorer=fuzz.token_set_ratio, limit=3)
			#print(fuzz_result_3tuple_list)
			fuzz_matched_q1 = fuzz_result_3tuple_list[0][0]
			fuzz_matched_q1_confidence = fuzz_result_3tuple_list[0][1]
			fuzz_matched_q2 = fuzz_result_3tuple_list[1][0]
			fuzz_matched_q2_confidence = fuzz_result_3tuple_list[1][1]
			fuzz_matched_q3 = fuzz_result_3tuple_list[2][0]
			fuzz_matched_q3_confidence = fuzz_result_3tuple_list[2][1]
			#print("fuzz_matched_question: ", fuzz_matched_question)
			#print("fuzz_match_confidence: ", fuzz_match_confidence)
			if fuzz_matched_q1_confidence < 60:
				print("\n\nNo luck. Please re-phrase your question or try another question")
			elif (fuzz_matched_q1_confidence == fuzz_matched_q2_confidence) and (fuzz_matched_q2_confidence == fuzz_matched_q3_confidence):
				#invoke pandas_dataframe_IR() 3 times in a loop with top 3 question indices
				answer_q1 = pandas_dataframe_IR(question_dict[fuzz_matched_q1], df)
				print("\nFound 3 results: \nShowing result for: \n", fuzz_matched_q1, " ", answer_q1, "\n")

				answer_q2 = pandas_dataframe_IR(question_dict[fuzz_matched_q2], df)
				print("Showing result for: \n", fuzz_matched_q2, " ", answer_q2, "\n")

				answer_q3 = pandas_dataframe_IR(question_dict[fuzz_matched_q3], df)
				print("Showing result for: \n", fuzz_matched_q3, " ", answer_q3, "\n")

			elif (fuzz_matched_q1_confidence == fuzz_matched_q2_confidence):
				#invoke pandas_dataframe_IR() 2 times in a loop with top 2 question indices
				answer_q1 = pandas_dataframe_IR(question_dict[fuzz_matched_q1], df)
				print("\nFound 2 results: \nShowing result for: \n", fuzz_matched_q1, " ", answer_q1, "\n")

				answer_q2 = pandas_dataframe_IR(question_dict[fuzz_matched_q2], df)
				print("Showing result for: \n", fuzz_matched_q2, " ", answer_q2, "\n")

			else:
				#invoke pandas_dataframe_IR() once
				answer_q1 = pandas_dataframe_IR(question_dict[fuzz_matched_q1], df)
				print("\nShowing result for: \n", fuzz_matched_q1, " ", answer_q1, "\n")

def pandas_dataframe_IR(question_index, df): #queries df and returns answer
	'''runs pandas statements on dataframe for the question asked, and returns the answer''' 
	day_of_week_index = {
			"Monday":1, 
			"Tuesday":2, 
			"Wednesday":3, 
			"Thursday":4, 
			"Friday":5, 
			"Saturday":6, 
			"Sunday":0 
			}
	if question_index == 1:		# "What is my current account balance ?"
		#start time 1:37pm
		#end time: 1:57pm
		#elapsed time: 20 mins

		# Strategy: in order to extract the current account balance, fetch the last 'closing_balance' cell value
		answer = df['closing_balance'].iloc[-1]
		return answer
	elif question_index == 2:	# "What was my balance at the ( start / beginning ) of this month ?"
		#NOTE: RETURNS THE CLOSING BALANCE OF THE FIRST DATE OF THIS MONTH
		#start time 1:59pm
		#end time: 4:09pm
		#elapsed time: 2h 10m		
		
		# Expected answer: 279065.59
		# Strategy: 1) find last date of last month 2) retrieve 'closing_balance' using this date 
		
		'''end_dates_of_months = []
		for date in df['date']:
			if date.is_month_end == True:
				end_dates_of_months.append(date)		
		answer = (df.loc[df['date'] == end_dates_of_months[-1]].closing_balance.iloc[-1])'''
		start_dates_of_months = []
		for date in df['date']:
			if date.is_month_start == True:
				if date not in start_dates_of_months:
					start_dates_of_months.append(date)		
		answer = (df.loc[df['date'] == start_dates_of_months[-1]].closing_balance.iloc[-1])
		return answer

	elif question_index == 3:
		# "What was my balance five (5) days back ?"
		#start time: 05:11pm
		#end time: 06:30pm
		#elapsed time: 1h20m	

		# Strategy: # date_five_days_back = current_date - 6 (5+1)
		#print(type(df['date']), df['date'])
		current_date = df['date'].unique()[-1]
		
		date_five_days_back = df['date'].unique()[-6]
		#print('current_date: ', current_date, "date_five_days_back: ", date_five_days_back)

		answer = (df.loc[df['date'] == date_five_days_back].closing_balance.iloc[-1])
		return answer
		
	elif question_index == 4:
		# "What was my balance at the ( start / beginning ) of this week ?"
		# expected answer: 446871.88 on 01-oct-2018
		#start time: 7:10pm
		#end time: 7:49pm
		#elapsed time: 	39m

		# Strategy: 
		# current_date = df['date'].unique()[-1]
		current_date = df['date'].iloc[-1]
		print("current_date: ", current_date)
		current_day = (df.loc[df['date'] == current_date].day.iloc[-1])
		print("current_day: ", current_day, "day_of_week_index[current_day]:", day_of_week_index[current_day])
		if day_of_week_index[current_day] == 0:
			go_back_by = 7
		else:
			go_back_by = day_of_week_index[current_day]
		start_of_week_date = df['date'].unique()[-go_back_by]
		print("start_of_week_date: ", start_of_week_date)
		
		answer = (df.loc[df['date'] == start_of_week_date].closing_balance.iloc[-1])
		return answer

	elif question_index == 401:
		# "What was my balance at the end of ( past / last ) week ?"
		# expected answer: 445871.88 on 30-sept-2018
		#start time: 7:55pm
		#end time: 8:02pm
		#elapsed time: 	7m

		# Strategy: 
		# current_date = df['date'].unique()[-1]
		current_date = df['date'].iloc[-1]
		print("current_date: ", current_date)
		current_day = (df.loc[df['date'] == current_date].day.iloc[-1])
		print("current_day: ", current_day, "day_of_week_index[current_day]:", day_of_week_index[current_day])
		if day_of_week_index[current_day] == 0:
			go_back_by = 7
		else:
			go_back_by = day_of_week_index[current_day]
		end_of_week_date = df['date'].unique()[-(go_back_by+1)]
		print("end_of_week_date: ", end_of_week_date)
		
		answer = (df.loc[df['date'] == end_of_week_date].closing_balance.iloc[-1])
		return answer

	elif question_index == 5:
		# "What was my balance last wednesday ?"
		#start time: 7:55pm
		#end time: 8:02pm
		#elapsed time: 	7m

		# Strategy: 
		current_date = df['date'].iloc[-1]
		print("current_date: ", current_date)
		current_day = (df.loc[df['date'] == current_date].day.iloc[-1])
		print("current_day: ", current_day, "day_of_week_index[current_day]:", day_of_week_index[current_day])
		'''if day_of_week_index[current_day] == 0:
			current_day_index = 7
		else:
			current_day_index = day_of_week_index[current_day]'''
		go_back_by = 7 - abs(day_of_week_index[current_day] - day_of_week_index["Wednesday"])
		last_wednesday_date = df['date'].unique()[-(go_back_by+1)] 
		print("last_wednesday_date: ", last_wednesday_date)
		answer = (df.loc[df['date'] == last_wednesday_date].closing_balance.iloc[-1])
		return answer

	elif question_index == 6:
		# "What is my average account balance over the ( last / past ) one ( 1 ) week ?"
		current_date = df['date'].iloc[-1]
		slice_start_date = df['date'].unique()[-7]
		slice_end_date = current_date
		print("slice_start_date: ", slice_start_date, " slice_end_date: ", slice_end_date)
		df = df[(df.date >= (slice_start_date)) & (df.date <= (slice_end_date))]
		
		answer = df['closing_balance'].mean()
		return answer
	elif question_index == 7:
		# "What is my average account balance over the ( last / past ) two ( 2 ) days ?"
		current_date = df['date'].iloc[-1]
		slice_start_date = df['date'].unique()[-2]
		slice_end_date = current_date
		print("slice_start_date: ", slice_start_date, " slice_end_date: ", slice_end_date)
		df = df[(df.date >= (slice_start_date)) & (df.date <= (slice_end_date))]
		
		answer = df['closing_balance'].mean()
		return answer
	elif question_index == 8:
		# "What is my average account balance over the ( last / past ) month ?"
		current_date = df['date'].iloc[-1]
		slice_start_date = df['date'].unique()[-30]
		slice_end_date = current_date
		print("slice_start_date: ", slice_start_date, " slice_end_date: ", slice_end_date)
		df = df[(df.date >= (slice_start_date)) & (df.date <= (slice_end_date))]
		
		answer = df['closing_balance'].mean()
		return answer
	elif question_index == 801:
		# "What is my average account balance at the end of the month ?"
		current_date = df['date'].iloc[-1]
		slice_start_date = df['date'].unique()[0]

		end_dates_of_months = []
		for date in df['date']:
			if date.is_month_end == True:
				if date not in end_dates_of_months:
					end_dates_of_months.append(date)		
		
		slice_end_date = end_dates_of_months[-1]
		print("slice_start_date: ", slice_start_date, " slice_end_date: ", slice_end_date)
		df = df[(df.date >= (slice_start_date)) & (df.date <= (slice_end_date))]
		
		answer = df['closing_balance'].mean()
		return answer
	elif question_index == 10:
		# "Which category has the highest spend this month ?"
		start_dates_of_months = []
		for date in df['date']:
			if date.is_month_start == True:
				if date not in start_dates_of_months:
					start_dates_of_months.append(date)		
		slice_start_date = start_dates_of_months[-1]
		slice_end_date = df['date'].iloc[-1]

		df = df[(df.date >= (slice_start_date)) & (df.date <= (slice_end_date))]
		
		print(df.groupby('category')['debit_amount'].sum())
		#print(df.groupby('category')['debit_amount'].sum().max())
		categorywise_series = (df.groupby('category')['debit_amount'].sum())
		#print("categorywise_series.shape", categorywise_series.shape)
		#print("categorywise_series.idxmax()", categorywise_series.idxmax())
		answer = categorywise_series.idxmax()
		return answer
	else:
		print ("\n\nResponse: \n\nSorry, I can't help you with that with my current capabilities. Please re-enter your question. \nTry entering: \nWhat is my current account balance?\nWhat was my balance at the start of the month?\nWhat was my balance five days back?\nWhat was my balance at the start of the week?\nWhat was my balance last wednesday?\nWhat is my average account balance over the past 1 week?\nWhat is my average account balance over the past 2 days?\nWhat is my average account balance over the past month?\nWhat is my average account balance at the end of the month?\nWhich category has the highest spend this month?\n")
		return

if __name__ == '__main__':
	# df = pd.read_csv("../input/aug01-2018-sept30-2018-banking-chatbot-dataset.csv", sep=',', index_col='Date', parse_dates=['Date'])
	df = pd.read_csv("../input/aug01-2018-sept30-2018-banking-chatbot-dataset.csv", sep=',')
	print("Checking for nulls:\n", df.isnull().sum())
	print('\nStandardizing column names')
	df.columns = [c.lower().replace(' ', '_') for c in df.columns]
	df['date']= pd.to_datetime(df['date'],format='%d/%m/%y')
	receive_user_questions(df)	#retrieve user questions in a loop