#!/usr/bin/env python
# coding: utf-8

# <img src="https://1.bp.blogspot.com/-qQryqABhdhA/XcC3lJupTKI/AAAAAAAAAzA/MOYu3P_DFRsmNkpjD9j813_SOugPgoBLACLcBGAsYHQ/s1600/h1.png" style="width:300px;hight:300px"/>

# ## In this notebook, I've just tested the Bert large uncase word masking finetuned model to see how it performs, this code is heavily based of ChrisMcCormickAI Bert series on youtube, I highly recommend to check it out [Link](https://www.youtube.com/watch?v=FKlPCK1uFrc&list=PLam9sigHPGwOBuH4_4fr-XvDbe5uneaf6)
# 

# In[ ]:


from transformers import TFBertForQuestionAnswering
import numpy as np

model = TFBertForQuestionAnswering.from_pretrained('bert-large-uncased-whole-word-masking-finetuned-squad')


# In[ ]:


from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained("bert-large-uncased-whole-word-masking-finetuned-squad")


# In[ ]:


def answer_question(question, answer_text):
    input_ids = tokenizer.encode(question, answer_text)

    print('Query has {:,} tokens.\n'.format(len(input_ids)))
    sep_index = input_ids.index(tokenizer.sep_token_id)

    num_seg_a = sep_index + 1

    num_seg_b = len(input_ids) - num_seg_a

    segment_ids = [0]*num_seg_a + [1]*num_seg_b

    assert len(segment_ids) == len(input_ids)

    start_scores, end_scores = model(np.array([input_ids]), # The tokens representing our input text.
                                    token_type_ids=np.array([segment_ids])) # The segment IDs to differentiate question from answer_text

    answer_start = np.argmax(start_scores)
    answer_end = np.argmax(end_scores)

    tokens = tokenizer.convert_ids_to_tokens(input_ids)

    answer = tokens[answer_start]

    for i in range(answer_start + 1, answer_end + 1):
        
        if tokens[i][0:2] == '##':
            answer += tokens[i][2:]
        
        else:
            answer += ' ' + tokens[i]

    print('Answer: "' + answer + '"')


# In[ ]:


import textwrap

# Wrap text to 80 characters.
wrapper = textwrap.TextWrapper(width=140) 

bert_abstract = "Barcelona's teenage forward Ansu Fati and all-time top scorer Lionel Messi were on target as they beat bottom club Leganes 2-0 at an empty Camp Nou on Tuesday to maintain their perfect start since the season resumed after its three-month hiatus.La Liga leaders Barca were far from their best and could have gone behind on two occasions before 17-year-old Fati put them ahead in the 43rd minute, firing through the legs of a defender and into the bottom corner for his fifth league goal of the season. Messi doubled Quique Setien's side's advantage from the penalty spot in the 69th minute, almost immediately after Antoine Griezmann had a goal ruled out for offside following a VAR review.Barca lead the standings on 64 points after 29 games, five ahead of nearest challengers Real Madrid who are in action at home to Valencia on Thursday. Leganes meanwhile are bottom with 23 points."
print(wrapper.fill(bert_abstract))


# In[ ]:


question = "who is the team that won the match?"

answer_question(question, bert_abstract)


# In[ ]:


question = "Who socred the first goal?"

answer_question(question, bert_abstract)


# In[ ]:


question = "how many point does Barcelona have?"

answer_question(question, bert_abstract)


# In[ ]:


question = "who is the second at la liga?"

answer_question(question, bert_abstract)


# In[ ]:


question = "What is the team that real madrid gonna face next?"

answer_question(question, bert_abstract)


# In[ ]:


question = "How old is ansu fati?"

answer_question(question, bert_abstract)


# In[ ]:


bert_abstract = "Let's first analyze the global figures that both players have produced throughout their career.We can see that Leo Messi's scoring average in his entire career (0.81) is 0.09 percentage points higher than Cristiano Ronaldo's (0.72).Cristiano Ronaldo has played 144 games more than Leo Messi in his entire career and has scored only 28 goals more than the argentinian. Also, Leo Messi has given 69 assists more than Cristiano Ronaldo in his entire career, making a total of 991 goals generated in 860 games (1.15 goals generated by game). Meanwhile, Cristiano Ronaldo has generated 950 goals in 1004 games, for a total of 0.95 goals generated by game in his entire career.Adding goals and assists we can affirm that, in his entire career, Leo Messi has generated 41 goals more than Cristiano Ronaldo, despite having played 144 matches less."
print(wrapper.fill(bert_abstract))


# In[ ]:



question = "Cristiano Ronaldo scoring average career goal?"

answer_question(question, bert_abstract)


# In[ ]:


question = "Who is better Messi or Cristiano Ronaldo?"

answer_question(question, bert_abstract)


# In[ ]:


get_ipython().system('pip install newspaper3k')


# In[ ]:


from newspaper import Article
url = "https://fox8.com/news/kanye-west-plans-to-run-for-president-of-the-united-states-has-2020-vision/"
article = Article(url)
article.download()
article.parse()
print(wrapper.fill(article.text))


# In[ ]:


question = "Who is Kanye West?"

answer_question(question, article.text)


# In[ ]:


question = "Who is Kanye West married to?"

answer_question(question, article.text)


# In[ ]:


question = "What is Kanye West plans for 2020?"

answer_question(question, article.text)


# ## this is indeed Impressive 

# In[ ]:




