#!/usr/bin/env python
# coding: utf-8

# 1. Naive check of 'Gene+Variation' values
# 
# 2. Note about variations with pattern 'Gene1-Gene2 Fusion'
# 
# # 1. Naive check of combinations 'Gene + Variation'
# 
# Import Pandas and read 'variants' files

# In[ ]:


import pandas as pd
df=pd.read_csv('../input/training_variants')
dfTest=pd.read_csv('../input/test_variants')


# Concatenate training and test datasets together

# In[ ]:


dfSum=pd.concat([df,dfTest])


# Introduce 'Gene + Variation' feature

# In[ ]:


dfSum['Gene_And_Variation']=dfSum['Gene']+' '+dfSum['Variation']
dfSum.head()


# Check dfSum info

# In[ ]:


dfSum.info()


# There are 3321 values for 'Class' (training set)
# 
# and 8989 values for all other features (training + test sets)
# 
# **Now checking number of unique values for 'Gene+Variation' combinations**

# In[ ]:


dfSum['Gene_And_Variation'].value_counts().head()


# In[ ]:


dfSum['Gene_And_Variation'].value_counts().max()


# ## Conclusion of Section 1:
# 
# All combinations 'Gene + Variation' in these datasets are unique

# # 2. Note about variations with pattern 'Gene1-Gene2 Fusion'
# 
# Introduce feature 'IsFusion' to tag all entries with variation of 'Gene1-Gene2 Fusion'

# In[ ]:


import numpy as np

def IsFusion(s):
    n = np.array(s.split()).size
    lastWord=s.split()[n-1]
    if (lastWord.lower()=='fusion'): return True
    return False

df['IsFusion']=df['Variation'].apply(lambda s: IsFusion(s))
df[df['IsFusion']==1].head()


# In the variations of the pattern 'Gene1-Gene2 Fusion' one of the gene is always the value from the 'Gene' column of the same row, or almost this value (279: NKX2-1 vs NKX2)
# 
# Is the second gene with the same fusion also present in the dataset? Not necessarily. But sometimes yes. Using code that is not quoted here, I found several fused 'Gene1-Gene2' pairs that appear twice in the training dataset.
# 
# Here are three examples:

# In[ ]:


df[df['Variation']=='TMPRSS2-ETV1 Fusion']


# In[ ]:


df[df['Variation']=='EWSR1-ETV1 Fusion']


# In[ ]:


df[df['Variation']=='ETV6-NTRK3 Fusion']


# Are 
# 
# 'Gene1, Gene1-Gene2 Fusion' 
# 
# and 
# 
# 'Gene2, Gene1-Gene2 Fusion'
# 
# entries identical?
# 
# **'Class' is always the same. What about text?**
# 
# 300|| Abstract The discovery of recurrent gene fusions in a majority of prostate cancers...
# 
# 978|| Abstract The discovery of recurrent gene fusions in a majority of prostate cancers...
# 
# 980||Sarcomas constitute some of the most aggressive adult and childhood malignancies...
# 
# 1060|| Fibroblast growth factors (FGFs) expressed in the apical ectodermal ridge (AER)...
# 
# 988||ETV6-NTRK3 (EN), a chimeric tyrosine kinase generated by t(12;15) translocations...
# 
# 3234||The congenital fibrosarcoma t(12;15)(p13;q25) rearrangement splices the ETV6 (TEL)...
# 
# **I didn't go deep into the text processing yet, but at least texts are not or not always identical.**
# 
# 

# In[ ]:




