#!/usr/bin/env python
# coding: utf-8

# # Loading data and Creating Submission File
# 
# You can solve the problem in any language and use either kaggle or your local machine. 
# 
# If you are using kaggle, you can activate a GPU instance using the Settings pane on the right panel.
# If you're using python on kaggle, here is how you load your data and submit your predictions.
# 
# Load the necessary libraries you need to handle your data and perform tasks

# In[ ]:


import numpy as np
import pandas as pd
import os
print(os.listdir("../input"))


# In[ ]:


data = pd.read_csv('../input/train.csv')
data.head()


# Once the data is loaded, perform all the tasks you need.
# 
# Now, Load the test set and perform all the necessary tasks and make the predictions

# In[ ]:


test = pd.read_csv('../input/test.csv')
test.head()


# In[ ]:


import random
pred = [random.random() for i in range(test.shape[0])]


# Create a new dataframe to store the submissions.
# 
# In the below example, the predictions are stored in the variable - ```pred```.

# In[ ]:


submission = pd.DataFrame()
submission['Id'] = test['Id']
submission['critical_temp'] = pred
submission.head()


# Write the dataframe to a csv file and make sure the ```index``` parameter is set to False.

# In[ ]:


submission.to_csv('random_sub.csv', index = False)
os.listdir()


# Once you are done with this, click on **Commit** on the top right side of the top bar. Now, the entire code will run(this might take some time). 
# 
# ![Commit and back](https://i.imgur.com/ifEfH1g.png)
# *You can see the commit and back button in the above image(Commit will continue to run even if you close your browser. For codes that take a long time to run, you can close the window/tab and ckeck on it later)*
# 
# You can either use the link that will be provided after the commit is done or you can click on the back button on the top, near the kernel's name. Here, you will be able to view your kernel. Click on the **Output** tab to view the file generated by the code and submit it to the competitions. 
# 
# 
# ![On commit](https://i.imgur.com/vJOeOKD.png)
# *This window will be visible when you commit*
# 
# ![Completed Commit](https://i.imgur.com/pLh4Cdf.png)
# *This window will be visible when the commit is done. Click on the link to see your kernel*
# 
# ![Kernel](https://i.imgur.com/HoLJQVV.png)
# *The kernel your committed. Your view might be different. Either way, check to see if your code has run properly and click on output*
# 
# ![Output Window](https://i.imgur.com/75XKuDz.png)
# *Click on Submit to competiton to make your submission*
# 
# 
# You are allowed only a limited number of submissions per day. So, use them wisely.
# 
# For help, check out the **Discussions** tab in the contest homepage.
