#!/usr/bin/env python
# coding: utf-8

# ## This Notebook is the second part of the Clustering of Research Papers.
# Step I : Unsupervised Clustering of Research Papers 
# 
# (Find the Notebook here: https://www.kaggle.com/debasmitadas/unsupervised-clustering-covid-research-papers)
# 
# Step II : Mapping the Clusters to the Sub-tasks given in the COVID Challenge

# ## Snapshot of Final Clusters of COVID-19 Research Papers

# ![image.png](attachment:image.png)

# ## Inputs:
# #### 1. Final Labelled Clusters of Research Papers in the COVID Challenge
# #### 2. File containing top 40 Research Papers for each Sub-Task, generated by cosine siilarity of embeddings of sub-tasks to Research Paper Title & Abstracts

# In[ ]:


import pandas as pd
import numpy as np


# In[ ]:


#Read the File with the Final Clusters
cluster_file_all = pd.read_csv('/kaggle/input/inputs-covid-clustering/Final_Clusters_Keywords.csv')

