#!/usr/bin/env python
# coding: utf-8

# In[ ]:


import pandas as pd
import scipy.stats as stats
import matplotlib.pyplot as plt
import seaborn as sns
get_ipython().run_line_magic('matplotlib', 'inline')


# In[ ]:


#You Could make this two columns anything you want, but I recommend leaving one as 'State'


# In[ ]:


def choose_cols(a,b):
    df = pd.read_csv('../input/elsect_summary.csv',)
    df = df[['YEAR',a,b]]
    df.dropna(how='any',inplace=True,)
    return df


# In[ ]:





# In[ ]:


def get_zscores(a):
    """
    Returns Z-Scores from a data frame input
    """
    a = sorted(a)
    z_scores = stats.zscore(a)
    z_scores.tolist()
    return z_scores

def get_pvals(b):
    """
    Returns pvals from list of zscores
    """
    p_vals = stats.norm.sf(abs(b))
    return p_vals

def plot_zscores(a,b):
    """
    Plots both zscores and pvalues. 
    Enter 'a' as your output from the zscores function
    Enter 'b' as your output from pvals function
    """
    plt.figure(figsize=(15,5))
    plt.scatter(a,b)
    plt.plot(a,b,'r',ls='-')
    plt.fill_between(a,b, where=b <= .05,color='g')
    plt.fill_between(a,b, where=b > .95)
    
def convert_to_df(data,name):
    """
    takes your lists generated by pvals and zscores function and returns a dataframe
    """
    df = pd.DataFrame(data,columns=name)
    return df

def bar_graph(a):
    plt.figure(figsize=(15,5))
    sns.countplot(a,data=sig)
    plt.xticks(rotation=45)


# In[ ]:


df = choose_cols('ENROLL','STATE')


# In[ ]:


x = get_zscores(df['ENROLL'])


# In[ ]:


y = get_pvals(x)


# In[ ]:


#Graph below shows the area that we are looking at. The green region are P-Values < 0.05


# In[ ]:


plot_zscores(x,y)


# In[ ]:


df_zscores = convert_to_df(x,['Zscores'])


# In[ ]:


df_pvals = convert_to_df(y,['P-Values'])


# In[ ]:


df.sort_values(by='ENROLL',inplace=True)
df.reset_index(inplace=True)


# In[ ]:


#Concatenates data frames from pvalues and zscores into on data frame for additional analysis


# In[ ]:


significance = pd.concat([df,df_zscores,df_pvals],axis=1)
significance.drop(['index'],axis=1,inplace=True)


# In[ ]:


#Return P-values only greater than 0.05


# In[ ]:


sig = significance[significance['P-Values']<=0.05]


# In[ ]:


sig.head()


# In[ ]:


#Years in which significanlty large populations were observed


# In[ ]:


bar_graph('YEAR')


# In[ ]:


#States in which significanlty large populations were observed


# In[ ]:


sns.barplot(x='STATE',y='ENROLL',data=sig)


# In[ ]:




