import time

greeting = "Hey Kagglers,\n"

print(greeting)
time.sleep(1)
print("We have streaming log output working again in the updated design for your kernel editor.")
time.sleep(1)
print("Thanks for your patience while we got this fixed - we understand many of you used this feature extensively while developing your kernel.\n")
time.sleep(1)
print("To see it working again,\n")
time.sleep(2)
print("1. Fork this kernel")
time.sleep(2)
print("2. Click 'Commit & Run in the top-right'")
time.sleep(2)
print("3. A new version with the commit in-flight should appear in the Versions section on the right.")
time.sleep(2)
print("4. Click this new version that's running and a modal will popup.")
time.sleep(2)
print("5. You should see these messages printing out in the log as the kernel executes top-to-bottom.\n")
time.sleep(5)
print("We have a bit more work to do on this modal before we show it by default when you click commit, so this should become even cleaner in the coming weeks.\n")
time.sleep(5)
print("You can also run your code interactively by selecting the line(s) you want to run and hitting shift+enter.\n")
time.sleep(5)
print("Thanks, and please let us know if you have any more feedback!")
time.sleep(1)
print(" _                       _       ")
time.sleep(1)
print("| |                     | |      ")
time.sleep(1)
print("| | __ ___   __ _  __ _ | | ___  ")
time.sleep(1)
print("| |/ /|__ \ / _` |/ _` || |/ _ \ ")
time.sleep(1)
print("|   < / _  | (_| | (_| || |  __/ ")
time.sleep(1)
print("|_|\_\\__,_|\__, |\__, ||_|\___| ")
time.sleep(1)
print("             __/ | __/ |    ")     
time.sleep(1)
print("            |___/ |___/     ")